### ISSUE TITLE
Gradle error when trying to build

### ISSUE THREAD

**Issue by bradh** [ossimlabs/omar-oms#51]
I'm trying to build using the instructions at https://github.com/ossimlabs/omar-oms#how-to-install-omar-oms-plugin-locally

The first parts (steps 1-4) of the process go OK.  I have set:
```
export OMAR_COMMON_PROPERTIES=/home/bradh/omar/omar-common/omar-common-properties.gradle 
```

I haven't set:
- OPENSHIFT_USERNAME
- OPENSHIFT_PASSWORD
- REPOSITORY_MANAGER_USER
- REPOSITORY_MANAGER_PASSWORD

I also added omar-video into the process, and it built OK.

However when I get to the last step in those instructions, I get:
```
bradh@minutae:~/omar/omar-oms/plugins/omar-oms-plugin$ gradle clean install

FAILURE: Build failed with an exception.

* Where:
Build file '/home/bradh/omar/omar-oms/build.gradle' line: 73

* What went wrong:
A problem occurred evaluating root project 'omar-oms'.
> Illegal null value provided in this collection: [login, null, -u, null, -p, null]

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 950ms
```

I'm not sure I understand the build system, but that looks like its trying to build for docker (or maybe openshift). I don't particularly need that, and would be happy just to have a local server if that is a better option

**Comment by walleyyang** [comment]
The instructions are outdated. It looks like you only need `omar-core` in the same level directory as `omar-oms` if you look at the `settings.gradle` file then `def modules`. You'll need to set a local environment variable called `O2_INLINE_BUILD` to true if you want to use the local OMAR resources. You should then be able to build while in `/omar-oms` using `./gradlew -p apps/omar-oms-app assemble`.

**Comment by bradh** [comment]
Thanks. That worked for me.

I can try drafting a PR if that might be useful.

**Comment by walleyyang** [comment]
No problem. Feel free to if you want, otherwise "hopefully" the next person that does work in the repo will update it.
